# -*- coding: utf-8 -*-
"""s1_ex1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12n1MWnhaDVQftbc9SA8KFwQoKohDfhW2
"""

# Program: Calculate total marks and percentage of a student

# Taking input marks for each subject using consistent variable naming
maths_marks = int(input("Enter your marks in Maths: "))
science_marks = int(input("Enter your marks in Science: "))
english_marks = int(input("Enter your marks in English: "))
social_marks = int(input("Enter your marks in Social: "))
economics_marks = int(input("Enter your marks in Economics: "))

# Calculate the total marks obtained
total_marks = (
    maths_marks +
    science_marks +
    english_marks +
    social_marks +
    economics_marks
)

# Calculate percentage (each subject out of 100)
percentage_value = (total_marks / 500) * 100

# Display the results
print("Total Marks:", total_marks)
print("Percentage:", percentage_value, "%")

