# -*- coding: utf-8 -*-
"""s1_ex5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RgY-HZCZzDToZS0cBYxRV50iiOt-HVux
"""

customer_name=input("Enter customer name")
order_number=input("Enter Order Number")
address=input("Enter Shipping Address")
delivery_date=input("Enter Delivery Date")
print(f'''Hello {customer_name},
We are happy to inform you that your order {order_number}
has been successfully shipped on {delivery_date} to:
{address}

Thank you for shopping with us!''')

