# -*- coding: utf-8 -*-
"""s1_ex4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AjAtPpu--LAG5Ajf2yzRQsuBi_DlA-0h
"""

Total_items=int(input("Enter the total number of items"))
items_per_page=int(input("Enter items per page"))
full_pages=Total_items//items_per_page
print(f"{full_pages} full pages")

