# -*- coding: utf-8 -*-
"""s1_ex3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rTNRLv-UcZfjhW2c8EjJo8KH5Mw9eVuO
"""

# Program: Perform arithmetic operations on two numbers

# Take input from the user
num1 = int(input("Enter 1st number: "))
num2 = int(input("Enter 2nd number: "))

# Perform arithmetic operations
addition = num1 + num2            # Addition of two numbers
subtraction = num1 - num2         # Subtraction of two numbers
multiplication = num1 * num2      # Multiplication of two numbers
division = num1 / num2            # Division of two numbers
modulus = num1 % num2             # Remainder after division
exponentiation = num1 ** num2     # num1 raised to the power num2
floor_division = num1 // num2     # Floor division (integer quotient)

# Display results
print("The sum of two numbers is:", addition)
print("The subtraction of two numbers is:", subtraction)
print("The multiplication of two numbers is:", multiplication)
print("The division of two numbers is:", division)
print("The modulus of two numbers is:", modulus)
print("The exponentiation of two numbers is:", exponentiation)
print("The floor division of two numbers is:", floor_division)