# -*- coding: utf-8 -*-
"""s2_ex1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zMFk5MXuGg4OplEOcrVk7RGayN2Caya_
"""

# vowel_checker.py
# Program to check whether an alphabet is a vowel or consonant

# Take input from user
alphabet = input("Enter an alphabet: ").lower()

# Check whether it is vowel or consonant
if alphabet in ['a', 'e', 'i', 'o', 'u']:
    print("Vowel")
else:
    print("Consonant")

