# -*- coding: utf-8 -*-
"""s2_ex2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oyfec1fxBCgg4hOWGi6EA3Or1OkSCcQr
"""

# bmi_interpreter.py
# Program: Calculate Body Mass Index (BMI) and display the weight category

# Step 1: Take user input for weight (in kilograms)
user_weight_kg = float(input("Enter your weight in kg: "))

# Step 2: Take user input for height (in meters)
user_height_m = float(input("Enter your height in meters: "))

# Step 3: Calculate BMI using the formula
# BMI = weight (kg) / (height (m))^2
calculated_bmi = user_weight_kg / (user_height_m ** 2)

# Step 4: Determine BMI category based on calculated value
if calculated_bmi < 18.5:
    # BMI less than 18.5 indicates underweight
    print("Underweight")
elif 18.5 <= calculated_bmi < 25:
    # BMI between 18.5 and 24.9 indicates normal weight
    print("Normal weight")
elif 25 <= calculated_bmi < 30:
    # BMI between 25 and 29.9 indicates overweight
    print("Overweight")
else:
    # BMI 30 or more indicates obesity
    print("Obese")

