# -*- coding: utf-8 -*-
"""s2_ex3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aWEPQzMxSozLCQ1EuxFjg9rwr0KWRhCI
"""

# Program: Menu-Driven Unit Converter
# Purpose: Convert temperature and length units based on user selection

# Step 1: Display the conversion menu to the user
print("Unit Converter Menu")
print("1. Fahrenheit to Celsius")
print("2. Celsius to Fahrenheit")
print("3. Centimeters to Inches")
print("4. Inches to Centimeters")

# Step 2: Take user's choice
user_choice = int(input("Enter your choice (1-4): "))

# Step 3: Perform conversion based on the selected option

# Option 1: Fahrenheit to Celsius
if user_choice == 1:
    # Take temperature in Fahrenheit
    fahrenheit_input = float(input("Enter temperature in Fahrenheit: "))

    # Convert to Celsius using formula
    celsius_output = (5 / 9) * (fahrenheit_input - 32)

    # Display result
    print("Converted value:", celsius_output, "°C")

# Option 2: Celsius to Fahrenheit
elif user_choice == 2:
    # Take temperature in Celsius
    celsius_input = float(input("Enter temperature in Celsius: "))

    # Convert to Fahrenheit using formula
    fahrenheit_output = (9 / 5) * celsius_input + 32

    # Display result
    print("Converted value:", fahrenheit_output, "°F")

# Option 3: Centimeters to Inches
elif user_choice == 3:
    # Take length in centimeters
    centimeters_input = float(input("Enter length in centimeters: "))

    # Convert to inches (1 inch = 2.54 cm)
    inches_output = centimeters_input / 2.54

    # Display result
    print("Converted value:", inches_output, "inches")

# Option 4: Inches to Centimeters
elif user_choice == 4:
    # Take length in inches
    inches_input = float(input("Enter length in inches: "))

    # Convert to centimeters (1 inch = 2.54 cm)
    centimeters_output = inches_input * 2.54

    # Display result
    print("Converted value:", centimeters_output, "cm")

# Step 4: Handle invalid choice
else:
    print("Invalid choice. Please select a number between 1 and 4.")