# -*- coding: utf-8 -*-
"""s2_ex4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Bm5Qz9iVbhJ6rAxB83vs1E8MWkmjaGV
"""

# Scholarship Eligibility Program
# Purpose: Determine scholarship eligibility based on GPA, extracurricular activities,
# and community service hours

# Step 1: Take GPA input from the user
student_gpa = float(input("Enter GPA: "))

# Step 2: Ask whether the student participated in extracurricular activities
participated_extracurricular = input(
    "Participated in extracurricular activities? (yes/no): "
).lower()

# Step 3: Take community service hours input
community_service_hours = int(input("Enter community service hours: "))

# Step 4: Check scholarship eligibility conditions

# First condition: GPA must be at least 3.5
if student_gpa < 3.5:
    print("No scholarship")

# Second condition: Must participate in extracurricular activities
elif participated_extracurricular != "yes":
    print("No scholarship")

# Third condition: Decide full or partial scholarship based on service hours
else:
    if community_service_hours >= 30:
        print("Award: Full Scholarship")
    else:
        print("Award: Partial Scholarship")

